# docker-compose.yml
version: "3.4"
services:
    server:
        build: ./Back-End
        hostname: back
        ports:
          - 8080:8080

    client:
        build: ./Front-End
        hostname: front
        ports:
          - 3000:3000
